### ISSUE TITLE
학습을 대략 몇 epoch정도 해야 그럭저럭 찾아지나요?

### ISSUE THREAD

**Issue by goodjian7** [DeepBaksuVision/You_Only_Look_Once#130]
VOC2012 train 데이터셋에 들어있는 대략 5000개 기준, batch size 16으로 했을 때 그냥저냥 찾아지는걸 눈으로 볼려면 몇 epoch까지 돌려야 되는지 궁금합니다. 1~2 epcoh돌려보는데 영 찾아지지가 않네요. readme.md 에 있는 그래프 x축이 1k,2k,3k 이렇게 되어 있는거 보면 epcoh를 최소 2K는 돌려야 되는것 같은데 의견을 구합니다. 

물어볼때가 없어서 issue에다가 씁니다.

**Comment by ssaru** [comment]
구현한지 꽤 되서 기억은 나지않지만, 저는 3-4일을 학습하고 결과를 확인하곤 했습니다. 
무난하게 3-4일 정도 학습을 돌려보시면 결과를 보실 수 있을겁니다.

**Comment by goodjian7** [comment]
고맙습니다! 그렇군요. 규모가 작은 데이터셋만 사용해 보가가 voc는 처음돌려봐서 한두 eoch만 돌려도 결과가 나오는줄 알았네요. 프리트레이닝 된 resnet백본을 가져다가 마지막 classifier만 초기화 해서 달고 트랜스퍼 러닝을 해보기도하고 darknet 코드 처럼 dense layer를 locally connected로 바꿔보고 이것저것 했는데도 잘 안되서 따로 문제가 있었나 했습니다. 그냥 얼마 안돌려서 그런거였나 보네요. 감사합니다

**Comment by ssaru** [comment]
네네 darknet의 경우도 적어도 3~7일 정도는 학습을 하셔야 결과를 보실 수 있으실겁니다.
도움이 되셨다니 다행입니다. ㅎㅎ
