### ISSUE TITLE
test.py에 있는 sigmoid

### ISSUE THREAD

**Issue by insurgent92** [DeepBaksuVision/You_Only_Look_Once#62]
https://github.com/DeepBaksuVision/YOLOv1/blob/b329af9d2c73660a84bd774992bddf98eca3f0d5/test.py#L11

이번 bugfix에서 test.py에 sigmoid function이 추가된 것을 확인했습니다.
혹시 이 함수가 필요한가요?

**Comment by ssaru** [comment]
필요없습니다.
bird 문제로 일시적으로 추가했었는데 
제가 삭제를 안하고 올렸네요..

앞으로 조금 주의해서 push하겠습니다.

**Comment by insurgent92** [comment]
@ssaru :D 아닙니다. 서로 돕는 것 아니겠습니까. 
https://github.com/DeepBaksuVision/YOLOv1/pull/64/commits/6d0cd6d4cbe4571ad02a22b17ecc40674644c1ab

#64 에 sigmoid function 삭제하는 부분까지 추가했습니다.
