### ISSUE TITLE
Unexpected key(s) in state_dict in Test.py (solved)

### ISSUE THREAD

**Issue by insurgent92** [DeepBaksuVision/You_Only_Look_Once#63]
pytorch version : 0.4.0 에서 
@ssaru 님이 주신 Checkpoint를 사용해서 Test.py 실행 시
다음과 같은 메시지 발생 후 프로그램이 종료됩니다. 

`Unexpected key(s) in state_dict: "module.layer1.1.num_batches_tracked",`   `"module.layer2.1.num_batches_tracked", "module.layer3.1.num_batches_tracked",`  `"module.layer4.1.num_batches_tracked", "module.layer5.1.num_batches_tracked",`  `"module.layer6.1.num_batches_tracked", "module.layer7.1.num_batches_tracked",`  `"module.layer8.1.num_batches_tracked", "module.layer9.1.num_batches_tracked",`  `"module.layer10.1.num_batches_tracked", "module.layer11.1.num_batches_tracked",`  `"module.layer12.1.num_batches_tracked", "module.layer13.1.num_batches_tracked",`  `"module.layer14.1.num_batches_tracked", "module.layer15.1.num_batches_tracked",`  `"module.layer16.1.num_batches_tracked", "module.layer17.1.num_batches_tracked",` `"module.layer18.1.num_batches_tracked", "module.layer19.1.num_batches_tracked",` `"module.layer20.1.num_batches_tracked", "module.layer21.1.num_batches_tracked",` `"module.layer22.1.num_batches_tracked", "module.layer23.1.num_batches_tracked",` `"module.layer24.1.num_batches_tracked".`

https://github.com/zhanghang1989/PyTorch-Encoding/issues/100
제가 지금까지 찾아본 이런 에러가 발생하는 이유로는

1. 모델을 DataParallel로 wrapping 하지 않은 경우 -> 해당사항 X
2. pytorch version이 다른 경우(가령 0.4.1로 학습한 모델이 0.4.0에서 돌아가지 않는 경우도 존재) 

가 있다고 합니다.

**Comment by ssaru** [comment]
제가 버전이 0.4.1입니다. ㅠㅠ
torch 버전을 0.4.1로 올려주시고 다시한번 실행시켜보시는게 어떠실까요?ㅠㅠ
