### ISSUE TITLE
train time에서 loss 출력 시 내용

### ISSUE THREAD

**Issue by insurgent92** [DeepBaksuVision/You_Only_Look_Once#79]
https://github.com/DeepBaksuVision/You_Only_Look_Once/blob/789ca233e8a6b821e84a9dfb0b58b0bcfffa989d/train.py#L144

1. format 하는 부분에서 {} 는 12개인데, 실제 인자는 13개 입니다. 
2. steop의 의미?

**Comment by ssaru** [comment]
1. 해당 부분은 수정하면 될 거 같습니다.
2. steop는 오타입니다

잘못했어요  :cry:
