### ISSUE TITLE
wandb 협업 하는 방법 찾기

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/You_Only_Look_Once#83]

**Comment by insurgent92** [comment]
@ssaru @chjeong530 
오늘 각자 랩탑으로 pytorch mnist example를 이용해서 
wandb로 협업을 어떻게 할 수 있을지 살펴보는건 어떨까요? 
wandb 설정/가입/학습/결과보기 까지 아주 간단하게 같이 해보면 좋을 것 같습니다.

**Comment by chjeong530** [comment]
네. 좋습니다. ㅎㅎㅎ

**Comment by ssaru** [comment]
저도 좋습니다! ㅎㅎ
