### ISSUE TITLE
Pull Request reviewer due problem 

### ISSUE THREAD

**Issue by insurgent92** [DeepBaksuVision/You_Only_Look_Once#94]
code/docs review도 task인데 task로 다루고 있지 않습니다. 
sprint7의 어떤 task가 해당 sprint 내에 PR/Merge가 가능하려면 sprint7 내에 reviewer가 review를 끝마쳐야 합니다. 그런데 가령 금요일이 미팅날인데 목요일 밤 늦게 task를 끝내고 PR를 날리는 경우는 생각해볼 수 있는데(물론 sprint due 이전이니, 현 시스템에서 문제될 상황은 아닙니다), reviewer 입장에서는 due date 하루짜리 task가 발생하는 것입니다.

단순하게 생각해본 해결방안으로는
sprint가 진행되는 일주일을  어떤 n 일로 쪼개서 (0 < n < 7) 
0 ~ n일 : PR 진행 
n ~ 7일 : review/merge 진행
을 하는게 어떻까 싶습니다.
이런 식으로 시스템적으로 나누는게 옳은건지는 모르겠습니다.

**Comment by ssaru** [comment]
괜찮은 방법인 것 같습니다.
sprint에 merge task 추가 및 스토리포인트 제한으로 해결하면 좋을 것 같습니다.

**Comment by ssaru** [comment]
PR은 reviewer 한명에 번갈아가면서 진행
